/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.universityapplication.universityapplication;

import com.universityapplication.universityapplication.models.BaseUser;
import com.universityapplication.universityapplication.models.CurrentUser;
import com.universityapplication.universityapplication.models.Subject;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexa
 */
public class StudentView extends javax.swing.JFrame {

    Connection conn = new MysqlConnection().mkDataBase();
    PreparedStatement pst;
    ResultSet rs;
    ArrayList<Subject> subjectList;
    ArrayList<Subject> userSubjectList;
    BaseUser user;
    CurrentUser current;
    boolean friend;

    public StudentView(CurrentUser currentuser, BaseUser user, boolean friend) throws SQLException {
        this.current = currentuser;
        this.user = user;
        this.friend = friend;
        this.subjectList = user.getUserSubjects();
        this.userSubjectList = currentuser.getUserSubjects();
        initComponents();
        checkFriend();
        setFieldValues();
        showSubjects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentName = new javax.swing.JLabel();
        stuudentSurname = new javax.swing.JLabel();
        friendButton = new javax.swing.JButton();
        studentEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        backStudentViewButton = new javax.swing.JButton();
        initials = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentName.setText("jLabel1");

        stuudentSurname.setText("jLabel1");

        friendButton.setText("jButton1");
        friendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendButtonActionPerformed(evt);
            }
        });

        studentEmail.setText("jLabel1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Subjects");

        backStudentViewButton.setText("Back");
        backStudentViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backStudentViewButtonActionPerformed(evt);
            }
        });

        initials.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(initials, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stuudentSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(studentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(friendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backStudentViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentName)
                    .addComponent(stuudentSurname)
                    .addComponent(friendButton)
                    .addComponent(studentEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(initials)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backStudentViewButton)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void friendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendButtonActionPerformed

        PreparedStatement pst; 
        try {
            if (!friend) {
                pst = conn.prepareStatement("INSERT INTO `friends` (`userId`, `friendId`) VALUES (?, ?);");
                pst.setInt(1, current.getId());
                pst.setInt(2, user.getId());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Added succesfully");
                friendButton.setText("Remove Friend");
            } else {
                pst = conn.prepareStatement("DELETE FROM `friends` WHERE userId=? and friendId=?;");
                pst.setInt(1, current.getId());
                pst.setInt(2, user.getId());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Removed  succesfully");
                friendButton.setText("Add Friend");

            }
            friend = !friend;
            checkFriend();
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_friendButtonActionPerformed

    private void backStudentViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backStudentViewButtonActionPerformed
        MainPage mainPage;
        try {
            mainPage = new MainPage(current);
            mainPage.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(StudentView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_backStudentViewButtonActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (checkMajor()) {
            int index = jList1.locationToIndex(evt.getPoint());
            SubjectAction action;
            boolean common = false;
            for (Subject subject : subjectList) {
                if (jList1.getModel().getElementAt(index).contains(subject.getName())) {
                    try {
                        if (jList1.getModel().getElementAt(index).contains("common")) {
                            common = true;
                        }
                        action = new SubjectAction(subject, common, current, user, friend);
                        action.setVisible(true);
                        dispose();
                    } catch (SQLException ex) {
                        Logger.getLogger(StudentView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    public boolean checkMajor() {
        return user.getMajor() == current.getMajor();
    }

    public void checkFriend() {
        jScrollPane1.setVisible(friend);
        jLabel1.setVisible(friend);
    }

    /**
     * @param args the command line arguments
     */
    void setFieldValues() {
        studentName.setText(user.getName());
        stuudentSurname.setText(user.getSurname());
        studentEmail.setText(user.getEmail());
        initials.setText(user.getInitials());
        if (friend) {
            friendButton.setText("Remove Friend");
        } else {
            friendButton.setText("Add Friend");
        }

    }

    void showSubjects() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Subject sub : subjectList) {
            String common = "";
            for (Subject el : userSubjectList) {
                if (el.getId() == sub.getId()) {
                    common = "(common)";
                    break;
                }
            }
            model.addElement(sub.getName() + " " + common);
        }
        jList1.setModel(model);
    }

    ;

    @Override
    public void dispose() {
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backStudentViewButton;
    private javax.swing.JButton friendButton;
    private javax.swing.JLabel initials;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel studentEmail;
    private javax.swing.JLabel studentName;
    private javax.swing.JLabel stuudentSurname;
    // End of variables declaration//GEN-END:variables
}
