/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.universityapplication.universityapplication;

import com.universityapplication.universityapplication.models.BaseUser;
import com.universityapplication.universityapplication.models.CurrentUser;
import com.universityapplication.universityapplication.models.Subject;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexa
 */
public class SubjectAction extends javax.swing.JFrame {

    Connection conn = new MysqlConnection().mkDataBase();
    int userId;
    int subjectId;
    String subjectName;
    CurrentUser current;
    BaseUser user;
    boolean same;
    boolean friend;

    public SubjectAction(Subject subject, boolean same, CurrentUser currentuser, BaseUser user, boolean friend) throws SQLException {
        this.current = currentuser;
        this.userId = currentuser.getId();
        this.user = user;
        this.subjectId = subject.getId();
        this.subjectName = subject.getName();
        this.same = same;
        this.friend = friend;
        initComponents();
        setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseName = new javax.swing.JLabel();
        setSubject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courseName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courseName.setText("jLabel1");

        setSubject.setText("jButton1");
        setSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(courseName)
                .addGap(61, 61, 61)
                .addComponent(setSubject)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSubjectActionPerformed
        PreparedStatement pst;
        try {
            if (!same) {
                pst = conn.prepareStatement("INSERT INTO `usersubject` (`userId`, `subjectId`) VALUES (?, ?);");
                pst.setInt(1, userId);
                pst.setInt(2, subjectId);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Added succesfully");
                setSubject.setText("Remove");

            } else {
                pst = conn.prepareStatement("DELETE FROM `usersubject` WHERE userId=? and subjectId=?;");
                pst.setInt(1, userId);
                pst.setInt(2, subjectId);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Removed  succesfully");
                setSubject.setText("Add");

            }
            StudentView studentview = new StudentView(current, user, friend);
            studentview.setVisible(true);
            this.setVisible(false);
            same = !same;

        } catch (SQLException ex) {
        }

    }//GEN-LAST:event_setSubjectActionPerformed

    /**
     * @param args the command line arguments
     */
    void setValues() {
        courseName.setText(subjectName);
        if (same) {
            setSubject.setText("Remove");
        } else {
            setSubject.setText("Add");
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseName;
    private javax.swing.JButton setSubject;
    // End of variables declaration//GEN-END:variables
}
